apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gestion-projet

resources:
  - configmap.yml
  - rollout.yml
  - frontend-service.yml

images:
  - name: nour292/frontend-auth
    newTag: "latest"